use_frameworks!

target 'GracefulImagePicker_Example' do
  pod 'GracefulImagePicker', :path => '../'

  target 'GracefulImagePicker_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.2.0'
  pod 'Nimble'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
